site_name: Dr. Alec McGregor
theme:
  name: material
  favicon: images/favicon-face-only.png
  language: en
  #icon:
  #  logo: images/android-chrome-512x512
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - search.highlight
    - search.share
    - search.suggest
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tops
    - navigation.tracking
    - navigation.tabs

  plugins:
    - typeset
    - search

  palette:

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

copyright: Copyright &copy; 2023 Alec McGregor 

extra:
  generator: true
  social:
  - icon: fontawesome/brands/youtube
    link: https://www.youtube.com/channel/UCPsM9Dlg6OGvWSYF2hVlm0A
  - icon: fontawesome/brands/twitter
    link: twitter.com
  - icon: fontawesome/brands/instagram
    link: www.instagram.com/aleclecleclec/
  - icon: fontawesome/brands/linkedin
    link: au.linkedin.com/in/alecmcg

nav:
  - Home: index.md
  - CV: cv.pdf
  - Photogrammetry:
    - photogrammetry/index.md
    - 'Basics': photogrammetry/basics.md
    - 'Coral Reefs': photogrammetry/coralreefs.md
    - 'Shipwrecks': photogrammetry/shipwrecks.md
    - 'AUVs': photogrammetry/auvs.md
  - Robotic Positioning:
    - roboticpositioning/index.md
  - Publications and Research:
    - publications/index.md
  - Dive Log:
    - divelog/dives_alec.html
  - Blog:
    - blog/index.md
    - 'Perth Shore Dives': blog/shoredives.md


